using System;
using System.Collections.Generic;
using System.Text;

namespace MovieLibraryTests
{
    class MovieLibraryMockup
    {
        internal static string[] ExpectedTopListAscending { get; } = {
  "Xiyouji zhi Nü'erguo",
  "Fifty Shades Freed",
  "Aiyaary",
  "Samson",
  "L'amant double",
  "Grottmannen Dug",
  "Nostalgia",
  "The Party",
  "Oh Lucy!",
  "The Boy Downstairs",
  "Black Panther",
  "Tehran Taboo",
  "Western",
  "Once Upon a Time in America",
  "Indiana Jones and the Last Crusade",
  "Loveless",
  "Mind Game",
  "The Third Man",
  "Chinatown",
  "Toy Story 3",
  "To Kill a Mockingbird",
  "The Treasure of the Sierra Madre",
  "L.A. Confidential",
  "Monty Python and the Holy Grail",
  "Rashomon",
  "Some Like It Hot",
  "All About Eve",
  "North by Northwest",
  "Citizen Kane",
  "M",
  "Vertigo",
  "Double Indemnity",
  "Aliens",
  "Taxi Driver",
  "American Beauty",
  "A Clockwork Orange",
  "Lawrence of Arabia",
  "Amélie",
  "Reservoir Dogs",
  "Das Boot",
  "Requiem for a Dream",
  "Eternal Sunshine of the Spotless Mind",
  "Full Metal Jacket",
  "Braveheart",
  "Bicycle Thieves",
  "Singin' in the Rain",
  "Metropolis",
  "Amadeus",
  "2001: A Space Odyssey",
  "The Sting",
  "The Apartment",
  "Raiders of the Lost Ark",
  "Rear Window",
  "Léon: The Professional",
  "Sunset Blvd.",
  "Apocalypse Now",
  "Memento",
  "Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb",
  "Alien",
  "The Shining",
  "Paths of Glory",
  "Django Unchained",
  "The Dark Knight Rises",
  "WALL·E",
  "The Lives of Others",
  "The Great Dictator",
  "Oldboy",
  "Princess Mononoke",
  "Witness for the Prosecution",
  "Once Upon a Time in the West",
  "Casablanca",
  "The Usual Suspects",
  "Psycho",
  "American History X",
  "Terminator 2: Judgment Day",
  "City Lights",
  "Modern Times",
  "Back to the Future",
  "The Pianist",
  "The Departed",
  "Gladiator",
  "The Intouchables",
  "The Prestige",
  "The Lion King",
  "Grave of the Fireflies",
  "Star Wars",
  "Seven Samurai",
  "City of God",
  "Se7en",
  "The Silence of the Lambs",
  "It's a Wonderful Life",
  "Saving Private Ryan",
  "Spirited Away",
  "Life Is Beautiful",
  "The Green Mile",
  "Star Wars: Episode V - The Empire Strikes Back",
  "One Flew Over the Cuckoo's Nest",
  "Goodfellas",
  "The Matrix",
  "Cinema Paradiso",
  "Star Wars: Episode VI - Return of the Jedi",
  "Pulp Fiction",
  "The Good, the Bad and the Ugly",
  "The Lord of the Rings: The Return of the King",
  "Fight Club",
  "The Lord of the Rings: The Fellowship of the Ring",
  "Inception",
  "Forrest Gump",
  "The Lord of the Rings: The Two Towers",
  "Schindler's List",
  "The Godfather: Part II",
  "The Dark Knight",
  "The Godfather",
  "The Shawshank Redemption",
  "12 Angry Men"
};

    }
}
